### PR TITLE
Qbllr/reflowing

### LINKED ISSUE #3: Fix row reflowing
sync pty.js and xterm with the proper number of characters within a row. Should be calculated from window-width some how. Make sure you handle the following: 
- [x] long prompts
- [x] full screen apps
- [x] line reflowing

### PR DESCRIPTION
**Pull request by qballer**
Once test pass should resolve #3

### CODE REVIEW

**Comment by qballer** [comment]
@imsnif some support on making tests pass would be great :)

**Comment by imsnif** [comment]
First - this is very cool. It's a great start, but there are still some issues here that have to be fixed:
1. "full screen" terminal applications, such as vim or alsamixer are broken by this. To see the problem, open vim - increase and decrease size.
2. Long prompts still get broken.

As for tests: for now, to get them to pass locally - you can create a mac directory, take screenshots of each test - confirm visually to make sure they're okay and then compare to them if the relevant environment variable is MAC (you can see it in the visual directory of the tests, it should be pretty straight forward. If not, let me know and I'll gladly walk you through it).
Travis is more of an issue, I'll do that once this is finished.

While this PR does make the situation objectively better, since we have to fix the above two issues (maybe more I haven't noticed?), I think it might be best to amend it and fix everything together. Mostly because updating the tests on travis is currently a very big pain. We need to find a better solution for that too, but that can wait. :)

All in all, very cool. Would love to see the above two issues fixed, and then will merge.

**Comment by qballer** [comment]
Back to the drawing board:
1. Full screen - xterm.js thinks it's in non existent line (off by one error in xterm array line).
2. long prompts - bummer, need to test that. 
3. xvfb doesn't work on mac, it used to be deployed by apple. Trying to use quarts, current FOSS port to mac of xvfb. I will try and make the tests work.

**Comment by imsnif** [comment]
Re: 3: xvfb is just a convenient thing so that windows don't pop-up at you while you're testing. So fix only if you feel like it.

**Pull request closed without merging**
